import express from 'express';
import c from '../controllers/admin.js';
import cloudinary from '../utils/cloudinary.js';
import { requireAuth } from '../middleware/auth/require_auth.js';
import { requireAdmin } from '../middleware/auth/require_admin.js';
const admin = express.Router();
admin.route('/').get(requireAuth, requireAdmin, c.get).post(requireAuth, requireAdmin, cloudinary.single('picture'), c.post);
admin.route('/complete-invitation').post(c.completeInvitation);
admin.route('/login').post(c.login);
admin.route('/logout').post(requireAuth, c.logout);
admin.route('/password-recovery/request').post(c.requestRecoveryCode);
admin.route('/password-recovery/verify').post(c.verifyRecoveryCode);
admin.route('/password-recovery/change-password').post(c.resetPassword);
admin.route('/:id').put(requireAuth, requireAdmin, c.put).delete(requireAuth, requireAdmin, c.delete);
admin.route('/:id/image').put(requireAuth, requireAdmin, cloudinary.single('picture'), c.uploadPicture);
export default admin;