import express from 'express';
import c from '../controllers/client.js';
import cloudinary from '../utils/cloudinary.js';
import { requireAuth } from '../middleware/auth/require_auth.js';
import { requireAdmin } from '../middleware/auth/require_admin.js';
import { requireAdminOrSelf } from '../middleware/auth/require_admin_or_self.js';
const client = express.Router();
client.route('/').get(requireAuth, requireAdmin, c.get).post(c.post);
client.route('/login').post(c.login);
client.route('/logout').post(requireAuth, c.logout);
client.route('/verify-email').post(c.verifyEmail);
client.route('/password-recovery/request').post(c.requestRecoveryCode);
client.route('/password-recovery/verify').post(c.verifyRecoveryCode);
client.route('/password-recovery/change-password').post(c.resetPassword);
client.route('/image').post(requireAuth, cloudinary.single('picture'), c.uploadPicture);
client.route('/:id').get(requireAuth, requireAdminOrSelf, c.getById).put(requireAuth, requireAdminOrSelf, c.put).delete(requireAuth, requireAdmin, c.delete);
export default client;