import express from 'express';
import c from '../controllers/collaborator.js';
import cloudinary from '../utils/cloudinary.js';
import { requireAuth } from '../middleware/auth/require_auth.js';
import { requireAdmin } from '../middleware/auth/require_admin.js';
const collaborator = express.Router();
collaborator.route('/').get(requireAuth, requireAdmin, c.get).post(requireAuth, requireAdmin, cloudinary.single('picture'), c.post);
collaborator.route('/login').post(c.login);
collaborator.route('/logout').post(requireAuth, c.logout);
collaborator.route('/complete-invitation').post(c.completeInvitation);
collaborator.route('/password-recovery/request').post(c.requestRecoveryCode);
collaborator.route('/password-recovery/verify').post(c.verifyRecoveryCode);
collaborator.route('/password-recovery/change-password').post(c.resetPassword);
collaborator.route('/:id').get(requireAuth, c.getById).put(requireAuth, c.put).delete(requireAuth, requireAdmin, c.delete);
collaborator.route('/:id/image').put(requireAuth, requireAdmin, cloudinary.single('picture'), c.uploadPicture);
export default collaborator;