import express from 'express';
import c from '../controllers/offer.js';
import { requireAuth } from '../middleware/auth/require_auth.js';
import { requireStaff } from '../middleware/auth/require_staff.js';
import { requireAdmin } from '../middleware/auth/require_admin.js';
const offer = express.Router();
offer.route('/').get(requireAuth, requireStaff, c.get).post(requireAuth, c.post);
offer.route('/:id').get(requireAuth, c.getById).delete(requireAuth, requireAdmin, c.delete);
offer.route('/:id/counter').post(requireAuth, c.counter);
offer.route('/:id/resolve').patch(requireAuth, c.resolve);
export default offer;