import { Router } from 'express';
import admin from './admin.js';
import auth from './auth.js';
import client from './client.js';
import collaborator from './collaborator.js';
import offer from './offer.js';
import property from './property.js';
const router = Router();
router.use('/admin', admin);
router.use('/auth', auth);
router.use('/client', client);
router.use('/collaborator', collaborator);
router.use('/offer', offer);
router.use('/property', property);
export default router;